name: Dart (Flutter) CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22'
          channel: 'stable'
      - name: Flutter Version
        run: flutter --version
      - name: Clean Project
        run: flutter clean
      - name: Get Dependencies
        run: flutter pub get
      - name: Build
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Analyze
        run: flutter analyze
#       - name: Tests
#         run: flutter test test/*
