name: Dart (Flutter) master CI

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build, test and release project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22'
          channel: 'stable'

      - name: Flutter version
        run: flutter --version

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Clean
        run: flutter clean

      - name: Download dependencies
        run: flutter pub get

      - name: Build
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run analyzer
        run: flutter analyze
